name: ForumSignin

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Sync with upstream
        if: github.repository != 'LovesAsuna/ForumSignin'
        continue-on-error: true
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.2
        with:
          upstream_sync_repo: LovesAsuna/ForumSignin
          upstream_sync_branch: master
          target_sync_branch: master
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_pull_args: '-s recursive -Xtheirs'

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Checkin
        env:
          ZDFX_COOKIE: ${{ secrets.ZDFX_COOKIE }}
          HUAHUO_COOKIE: ${{ secrets.HUAHUO_COOKIE }}
        run: go run .
